version: '3.8'
services:
  seq:
    container_name: dotnetarchitecture_seq
    image: datalust/seq:latest
    ports:
      - 80:80 # url to seq
      - 5341:5341
    environment:
      ACCEPT_EULA: Y
    networks:
      - dotnetarchitecture
  postgres:
    container_name: dotnetarchitecture_postgres
    image: postgres
    env_file:
      - .env

    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - dotnetarchitecture
    restart: unless-stopped
networks:
  dotnetarchitecture:
    driver: bridge
volumes:
  postgres:
