name: Branch Protection

on:
  push:
    branches-ignore:
      - main

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure branch protection
        uses: peter-evans/create-or-update-branch-protection@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          strict: true
          enforce_admins: true
          require_up_to_date: true
