name: deploy
run-name: Deploying to ECR triggered by commit "${{ github.event.head_commit.message }}"(${{ github.sha }})
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'infrastructure/**'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Restore
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REGISTRY_TOKEN: ${{ github.token }}
        run: make restore

      - name: publish
        shell: bash
        run: make publish

      - name: Upload published file
        uses: actions/upload-artifact@v3
        with:
          name: dll-artifacts
          path: .publish/

  dockerize:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
          aws-region: aws-region-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: vertical-slice
          IMAGE_TAG: ${{ github.sha }}
        run: |
          make image REGISTRY=$REGISTRY REPOSITORY=$REPOSITORY IMAGE_TAG=$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}
