name: deploy
run-name: Deploying to ECR triggered by commit "${{ github.event.head_commit.message }}"(${{ github.sha }})
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'infrastructure/**'
env:
  artificate-token: ${{ github.run_id }}-${{ github.run_attempt }}
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    outputs:
      publish: ${{ steps.publish.outputs.dir }}
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Restore
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REGISTRY_TOKEN: ${{ github.token }}
        run: make restore

      - name: publish
        id: publish
        shell: bash
        run: make publish

      - name: Upload published file
        uses: actions/upload-artifact@v3
        with:
          name: dll-artifacts-${{ env.artificate-token }}
          path: .publish/

  dockerize:
    needs: build-and-publish
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: dotnetarchitecture-ecr-repo
      IMAGE_NAME: clean-slice
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Download published output
        uses: actions/download-artifact@v2
        with:
          name: dll-artifacts-${{ env.artificate-token }}
          path: ./.publish

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
          aws-region: aws-region-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build image
        id: image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: docker build -t $(IMAGE_NAME):$(IMAGE_TAG) -f ./infrastructure/Dockerfile .

      - name: Tag and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag my-app:${IMAGE_NAME} $REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}
          docker push $REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}
