name: pull-request
run-name: Test and validate pull request done by ${{ github.actor }} on ${{ github.head_ref }} branch
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Run make build
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REGISTRY_TOKEN: ${{ github.token }}
        run: make all CONFIGURATION=Release

      - name: Test all
        shell: bash
        run: make test
